opt_in_rules:
  - legacy_random
  - private_action
  - private_outlet
  - unneeded_parentheses_in_closure_argument
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
excluded:
  - ./Prefecture23-10-03/AppDelegate.swift
  - ./Prefecture23-10-03/SceneDelegate.swift
